services:
  frontend:
    build: ./FrontEnd
    env_file:
      - ./FrontEnd/.env
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
      - meme-network
  backend:
    build: ./backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    networks:
      - meme-network
    
networks:
  meme-network:
    driver: bridge
     
    
