name: meme-deployment
on:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }} 
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
      IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
      IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: copying files
        uses: actions/checkout@v2
      - name: creating .env
        run: |
          echo VITE_API_BASE_URL=$VITE_API_BASE_URL > ./FrontEnd/.env
          
          echo PORT=$PORT > ./backend/.env
          echo MONGODB_URI=$MONGODB_URI >> ./backend/.env
          echo IMAGEKIT_PUBLIC_KEY=$IMAGEKIT_PUBLIC_KEY >> ./backend/.env
          echo IMAGEKIT_PRIVATE_KEY=$IMAGEKIT_PRIVATE_KEY >> ./backend/.env
          echo IMAGEKIT_URL_ENDPOINT=$IMAGEKIT_URL_ENDPOINT >> ./backend/.env
          echo JWT_SECRET=$JWT_SECRET >> ./backend/.env
      - name: ssh into ec2
        uses: appleboy/scp-action@v1
        with:
           host: ${{ secrets.HOST }}
           username:  ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           source: .
           target: /home/ec2-user/MemePool
      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@v1
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           script: |
             cd /home/ec2-user/MemePool
             docker-compose up  -d
      
        
